export const GET_PRE_MATCH_SUMMARY="GET_PRE_MATCH_SUMMARY"
export const GET_PRE_MATCH_SUMMARY_SUCCESS="GET_PRE_MATCH_SUMMARY_SUCCESS"
export const GET_PRE_MATCH_SUMMARY_FAILED="GET_PRE_MATCH_SUMMARY_FAILED"

export const GET_MATCH_STATS="GET_MATCH_STATS"
export const GET_MATCH_STATS_SUCCESS="GET_MATCH_STATS_SUCCESS"
export const GET_MATCH_STATS_FAILED="GET_MATCH_STATS_FAILED"

export const GET_MATCH_PREVIEW="GET_MATCH_PREVIEW"
export const GET_MATCH_PREVIEW_SUCCESS="GET_MATCH_PREVIEW_SUCCESS"
export const GET_MATCH_PREVIEW_FAILED="GET_MATCH_PREVIEW_FAILED"

export const GET_MATCH_LINEUP="GET_MATCH_LINEUP"
export const GET_MATCH_LINEUP_SUCCESS="GET_MATCH_LINEUP_SUCCESS"
export const GET_MATCH_LINEUP_FAILED="GET_MATCH_LINEUP_FAILED"

export const GET_MATCH_REPORT="GET_MATCH_REPORT"
export const GET_MATCH_REPORT_SUCCESS="GET_MATCH_REPORT_SUCCESS"
export const GET_MATCH_REPORT_FAILED="GET_MATCH_REPORT_FAILED"

export const GET_MATCH_COMMENTARY="GET_MATCH_COMMENTARY"
export const GET_MATCH_COMMENTARY_SUCCESS="GET_MATCH_COMMENTARY_SUCCESS"
export const GET_MATCH_COMMENTARY_FAILED="GET_MATCH_COMMENTARY_FAILED"

export const GET_MATCH_TEST="GET_MATCH_TEST"
export const GET_MATCH_TEST_SUCCESS="GET_MATCH_TEST_SUCCESS"
export const GET_MATCH_TEST_FAILED="GET_MATCH_TEST_FAILED"