export const GET_ALL_TOURNS="GET_ALL_TOURNS"
export const GET_ALL_TOURNS_SUCCESS="GET_ALL_TOURNS_SUCCESS"
export const GET_ALL_TOURNS_FAILED="GET_ALL_TOURNS_FAILED"
export const GET_ALL_TOURNS_BY_CAT="GET_ALL_TOURNS_BY_CAT"
export const GET_ALL_TOURNS_BY_CAT_SUCCESS="GET_ALL_TOURNS_BY_CAT_SUCCESS"
export const GET_ALL_TOURNS_BY_CAT_FAILED="GET_ALL_TOURNS_BY_CAT_FAILED"

export const GET_ALL_TEAMS="GET_ALL_TEAMS"
export const GET_ALL_TEAMS_SUCCESS="GET_ALL_TEAMS_SUCCESS"
export const GET_ALL_TEAMS_FAILED="GET_ALL_TEAMS_FAILED"


export const SET_FAV_COUNTRY="SET_FAV_COUNTRY"
export const SET_FAV_COUNTRY_SUCCESS="SET_FAV_COUNTRY_SUCCESS"
export const SET_FAV_COUNTRY_FAILED="SET_FAV_COUNTRY_FAILED"


export const GET_FAV_COMPET_TEAMS="GET_FAV_COMPET_TEAMS"
export const GET_FAV_COMPET_TEAMS_SUCCESS="GET_FAV_COMPET_TEAMS_SUCCESS"
export const GET_FAV_COMPET_TEAMS_FAILED="GET_FAV_COMPET_TEAMS_FAILED"

export const GET_DATE_MATCHES="GET_DATE_MATCHES"
export const GET_DATE_MATCHES_SUCCESS="GET_DATE_MATCHES_SUCCESS"
export const GET_DATE_MATCHES_FAILED="GET_DATE_MATCHES_FAILED"

export const GET_MATCHES_SCORES="GET_MATCHES_SCORES"
export const GET_MATCHES_SCORES_SUCCESS="GET_MATCHES_SCORES_SUCCESS"
export const GET_MATCHES_SCORES_FAILED="GET_MATCHES_SCORES_FAILED"