export const REGISTER_USER="REGISTER_USER"
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILED="REGISTER_USER_FAILED"

export const LOGIN_USER="LOGIN_USER"
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILED="LOGIN_USER_FAILED"

export const SET_FAV_COMPT_TEAMS="SET_FAV_COMPT_TEAMS"
export const SET_FAV_COMPT_TEAMS_SUCCESS="SET_FAV_COMPT_TEAMS_SUCCESS"
export const SET_FAV_COMPT_TEAMS_FAILED="SET_FAV_COMPT_TEAMS_FAILED"


export const GET_SEARCH_CONTENT="GET_SEARCH_CONTENT"
export const GET_SEARCH_CONTENT_SUCCESS="GET_SEARCH_CONTENT_SUCCESS"
export const GET_SEARCH_CONTENT_FAILED="GET_SEARCH_CONTENT_FAILED"
